config:
  backup: true
  banner: true
  create: true
  dotpath: .
  ignoreempty: false
dotfiles:
  f_ghostty:
    src: .config/ghostty/config.ghostty
    dst: ~/.config/ghostty/config.ghostty
  f_config.ghostty:
    src: config/ghostty/config.ghostty
    dst: ~/.config/ghostty/config.ghostty
  f_ml4w-wallpaper:
    src: .config/ml4w/scripts/ml4w-wallpaper
    dst: ~/.config/ml4w/scripts/ml4w-wallpaper
  f_wallpaper-folder:
    src: .config/ml4w/settings/wallpaper-folder
    dst: ~/.config/ml4w/settings/wallpaper-folder
  f_wallpaper-automation:
    src: .config/ml4w/settings/wallpaper-folder
    dst: ~/.config/ml4w/settings/wallpaper-automation
  f_wallpaper-effect:
    src: .config/ml4w/settings/wallpaper-folder
    dst: ~/.config/ml4w/settings/wallpaper-effect
  f_scripts_ml4w-wallpaper:
    src: config/ml4w/scripts/ml4w-wallpaper
    dst: ~/.config/ml4w/scripts/ml4w-wallpaper
    chmod: '755'
  f_settings_wallpaper-folder:
    src: config/ml4w/settings/wallpaper-folder
    dst: ~/.config/ml4w/settings/wallpaper-folder
  f_settings_wallpaper-automation:
    src: config/ml4w/settings/wallpaper-automation
    dst: ~/.config/ml4w/settings/wallpaper-automation
  f_settings_wallpaper-effect:
    src: config/ml4w/settings/wallpaper-effect
    dst: ~/.config/ml4w/settings/wallpaper-effect
  d_ml4w:
    src: .config/ml4w
    dst: ~/.config/ml4w
  f_terminal.sh:
    src: .config/ml4w/settings/terminal.sh
    dst: ~/.config/ml4w/settings/terminal.sh
    chmod: '755'
profiles:
  home:
    dotfiles:
    - f_ghostty
    - d_ml4w
    - f_terminal.sh
  ghostty:
    dotfiles:
    - f_ghostty
    - f_terminal.sh
  ml4w-wallpaper:
    dotfiles:
    - d_ml4w
