config:
  backup: true
  banner: true
  create: true
  dotpath: .
  ignoreempty: false
dotfiles:
  f_kitty:
    src: .config/kitty/kitty.conf
    dst: ~/.config/kitty/kitty.conf
  f_kitty-matugen:
    src: .config/kitty/colors-matugen.conf
    dst: ~/.config/kitty/colors-matugen.conf
  f_ml4w-wallpaper:
    src: .config/ml4w/scripts/ml4w-wallpaper
    dst: ~/.config/ml4w/scripts/ml4w-wallpaper
  f_wallpaper-folder:
    src: .config/ml4w/settings/wallpaper-folder
    dst: ~/.config/ml4w/settings/wallpaper-folder
  f_wallpaper-automation:
    src: .config/ml4w/settings/wallpaper-folder
    dst: ~/.config/ml4w/settings/wallpaper-automation
  f_wallpaper-effect:
    src: .config/ml4w/settings/wallpaper-folder
    dst: ~/.config/ml4w/settings/wallpaper-effect
  f_scripts_ml4w-wallpaper:
    src: config/ml4w/scripts/ml4w-wallpaper
    dst: ~/.config/ml4w/scripts/ml4w-wallpaper
    chmod: '755'
  f_settings_wallpaper-folder:
    src: config/ml4w/settings/wallpaper-folder
    dst: ~/.config/ml4w/settings/wallpaper-folder
  f_settings_wallpaper-automation:
    src: config/ml4w/settings/wallpaper-automation
    dst: ~/.config/ml4w/settings/wallpaper-automation
  f_settings_wallpaper-effect:
    src: config/ml4w/settings/wallpaper-effect
    dst: ~/.config/ml4w/settings/wallpaper-effect
  d_ml4w:
    src: .config/ml4w
    dst: ~/.config/ml4w
  f_terminal.sh:
    src: .config/ml4w/settings/terminal.sh
    dst: ~/.config/ml4w/settings/terminal.sh
    chmod: '755'
  d_hypr:
    src: .config/hypr
    dst: ~/.config/hypr
  f_default.lua:
    src: .config/hypr/conf/decorations/default.lua
    dst: ~/.config/hypr/conf/decorations/default.lua
  f_fastfetch:
    src: .config/fastfetch/config.jsonc
    dst: ~/.config/fastfetch/config.jsonc
profiles:
  home:
    dotfiles:
    - d_ml4w
    - f_terminal.sh
    - f_default.lua
    - f_fastfetch
    - f_kitty
    - f_kitty-matugen
  kitty:
    dotfiles:
    - f_kitty
    - f_kitty-matugen
  ml4w-wallpaper:
    dotfiles:
    - d_ml4w
  hypr:
    dotfiles:
    - d_hypr
